---
apiVersion: v1
kind: Service
metadata:
  name: hrapploginservice
spec:
  ports:
   - port: 8181
     targetPort: 8181
     nodePort: 30503
  selector:
    app: hrapplogin
  type: NodePort
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hrapplogin
spec:
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: hrapplogin
    spec:
      containers:
      - name: hrapplogin
        image: harlinmani/loginwithmongo:kuber
        
        ports:
        - containerPort: 80