package com.stpl.hr.onboard.domain.query.constants;

public class OnboardMsDomainQueryConstant {
	private OnboardMsDomainQueryConstant() {
		super();
	}

	public static final String ONBOARD_ASSOCIATE_INSERT_QUERY = "INSERT INTO THR_ONBOARD_QUERY_ASSOCIATE (ASSOCIATE_ID,AGGREGATE_ID,FIRST_NAME,LAST_NAME,MOBILE_NO,EMAIL_ID,HIGHEST_DEGREE,CGPA,COLLEGE_NAME,PREVIOUS_EMPLOYER,YEAR_OF_EXPERIENCE,BUSINESS_UNIT,ASSOCIATE_ROLE,ASSOCIATE_DESIGNATION,JOINING_DATE,USER_NAME,STATUS,ASSET_INFO) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
	public static final String ONBOARD_ASSOCIATE_SELECT_QUERY = "Select SYSTEM_ID,ASSOCIATE_ID,AGGREGATE_ID,FIRST_NAME,LAST_NAME,MOBILE_NO,EMAIL_ID,HIGHEST_DEGREE,CGPA,COLLEGE_NAME,PREVIOUS_EMPLOYER,YEAR_OF_EXPERIENCE,BUSINESS_UNIT,ASSOCIATE_ROLE,ASSOCIATE_DESIGNATION,JOINING_DATE,STATUS,ASSET_INFO from THR_ONBOARD_QUERY_ASSOCIATE WHERE ASSOCIATE_ID =?;";
	public static final String ONBOARD_ASSOCIATE_SELECT_ALL_QUERY = "Select SYSTEM_ID,ASSOCIATE_ID,AGGREGATE_ID,FIRST_NAME,LAST_NAME,MOBILE_NO,EMAIL_ID,HIGHEST_DEGREE,CGPA,COLLEGE_NAME,PREVIOUS_EMPLOYER,YEAR_OF_EXPERIENCE,BUSINESS_UNIT,ASSOCIATE_ROLE,ASSOCIATE_DESIGNATION,JOINING_DATE,STATUS,ASSET_INFO,USER_NAME from THR_ONBOARD_QUERY_ASSOCIATE;";
	public static final String ONBOARD_ASSOCIATE_SELECT_LATEST_ASSOCIATE = "Select max(ASSOCIATE_ID) from THR_ONBOARD_QUERY_ASSOCIATE;";
	public static final String ONBOARD_ASSOCIATE_SELECT_QUERY_BY_AGGREAGETID = "Select SYSTEM_ID,ASSOCIATE_ID,AGGREGATE_ID,FIRST_NAME,LAST_NAME,MOBILE_NO,EMAIL_ID,HIGHEST_DEGREE,CGPA,COLLEGE_NAME,PREVIOUS_EMPLOYER,YEAR_OF_EXPERIENCE,BUSINESS_UNIT,ASSOCIATE_ROLE,ASSOCIATE_DESIGNATION,JOINING_DATE,STATUS,ASSET_INFO from THR_ONBOARD_QUERY_ASSOCIATE WHERE AGGREGATE_ID =? AND STATUS=?;";

}
