---
apiVersion: v1
kind: Service
metadata:
  name: hrappmongoservice
spec:
  ports:
   - port: 27017
     targetPort: 27017
     nodePort: 30502
  selector:
    app: hrappmongodb
  type: NodePort
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hrappmongodb
spec:
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: hrappmongodb
    spec:
      containers:
      - name: hrappmongodb
        image: santanukm/mongocommon:v1.0
        
        ports:
        - containerPort: 80