---
apiVersion: v1
kind: Service
metadata:
  name: hrappassetservice
spec:
  ports:
   - port: 8181
     targetPort: 8181
     nodePort: 30505
  selector:
    app: hrappasset
  type: NodePort
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hrappasset
spec:
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: hrappasset
    spec:
      containers:
      - name: hrappasset
        image: santanukm/assetwithmongo:kuber
        
        ports:
        - containerPort: 80