---
apiVersion: v1
kind: Service
metadata:
  name: hrappassetlogicservice
spec:
  ports:
   - port: 8181
     targetPort: 8181
     nodePort: 30505
  selector:
    app: hrappassetlogic
  type: NodePort
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hrappassetlogic
spec:
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: hrappassetlogic
    spec:
      containers:
      - name: hrappassetlogic
        image: santanukm/assetwithmongo:logic
        
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/apache-servicemix-7.0.1/etc/secrets/
          readOnly: false
          name: stplsecret-storage
      volumes:
      - name: stplsecret-storage
        secret:
          secretName: stplsecret
          items:
          - key: com.stpl.assetms.query.cfg
            path: com.stpl.assetms.query.cfg
          - key: com.stpl.assetms.command.cfg
            path: com.stpl.assetms.command.cfg
          - key: com.stpl.assetms.eventstore.cfg
            path: com.stpl.assetms.eventstore.cfg
          - key: com.stpl.assetms.mvc.cfg
            path: com.stpl.assetms.mvc.cfg