---
apiVersion: v1
kind: Service
metadata:
  name: hrapponboardlogicservice
spec:
  ports:
   - port: 8181
     targetPort: 8181
     nodePort: 30504
  selector:
    app: hrapponboardlogic
  type: NodePort
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hrapponboardlogic
spec:
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: hrapponboardlogic
    spec:
      containers:
      - name: hrapponboardlogic
        image: santanukm/onboardwithmongo:logic
        
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/apache-servicemix-7.0.1/etc/secrets/
          readOnly: false
          name: stplsecret-storage
      volumes:
      - name: stplsecret-storage
        secret:
          secretName: stplsecret
          items:
          - key: com.stpl.onboardms.query.cfg
            path: com.stpl.onboardms.query.cfg
          - key: com.stpl.onboardms.command.cfg
            path: com.stpl.onboardms.command.cfg
          - key: com.stpl.onboardms.eventstore.cfg
            path: com.stpl.onboardms.eventstore.cfg
          - key: com.stpl.onboardms.mvc.cfg
            path: com.stpl.onboardms.mvc.cfg