---
apiVersion: v1
kind: Service
metadata:
  name: hrapploginlogicservice
spec:
  ports:
   - port: 8181
     targetPort: 8181
     nodePort: 30503
  selector:
    app: hrapploginlogic
  type: NodePort
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hrapploginlogic
spec:
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: hrapploginlogic
    spec:
      containers:
      - name: hrapploginlogic
        image: santanukm/hrloginms:logic
        
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/apache-servicemix-7.0.1/etc/secrets/
          readOnly: false
          name: stplsecret-storage
      volumes:
      - name: stplsecret-storage
        secret:
          secretName: stplsecret
          items:
          - key: com.stpl.loginms.query.cfg
            path: com.stpl.loginms.query.cfg
          - key: com.stpl.loginms.command.cfg
            path: com.stpl.loginms.command.cfg
          - key: com.stpl.loginms.eventstore.cfg
            path: com.stpl.loginms.eventstore.cfg
          - key: com.stpl.loginms.mvc.cfg
            path: com.stpl.loginms.mvc.cfg