---
apiVersion: v1
kind: Service
metadata:
  name: hrappcommonuiservice
spec:
  ports:
   - port: 8181
     targetPort: 8181
     nodePort: 30600
  selector:
    app: hrappcommonui
  type: NodePort
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hrappcommonui
spec:
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: hrappcommonui
    spec:
      containers:
      - name: hrappcommonui
        image: santanukm/commonmsui:ui
        
        ports:
        - containerPort: 80