---
apiVersion: v1
kind: Service
metadata:
  name: hrapponboardservice
spec:
  ports:
   - port: 8181
     targetPort: 8181
     nodePort: 30504
  selector:
    app: hrapponboard
  type: NodePort
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hrapponboard
spec:
  
  replicas: 1
  
  template:
    metadata:
      labels:
        app: hrapponboard
    spec:
      containers:
      - name: hrapponboard
        image: harlinmani/onboardwithmongo:kuber
        
        ports:
        - containerPort: 80